.

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -38,7 +38,8 @@ jobs:
           tag_name: v${{ inputs.tag }}
 
   push-to-registry:
-    # This action doesn't need to wait on any other task, it's easy to re-tag if something failed
+    # This action doesn't need to wait on any other task, it's easy to re-tag if something failed and we're validating
+    # the tag here also
     name: "Push Docker image to Docker Hub"
     runs-on: "ubuntu-latest"
     environment:
@@ -47,12 +48,6 @@ jobs:
       - uses: actions/checkout@v4
         with:
           ref: ${{ inputs.sha }}
-
-      - name: "Get tag"
-        id: get-tag
-        shell: bash
-        run: |
-          echo PKG_VERSION=$(cargo metadata --format-version 1 | jq -r '.packages[] | select(.name=="ruff_cli") | .version') >> $GITHUB_OUTPUT
 
       - uses: docker/setup-buildx-action@v3
 
@@ -68,6 +63,21 @@ jobs:
         with:
           images: ghcr.io/konstin/release-testing2
 
+      - name: Check tag consistency
+        # Unlike validate-tag we don't check if the commit is on the main branch, but given docker is re-tag-able this
+        # seems good enough
+        if: ${{ inputs.tag }}
+        run: |
+          version=$(grep "version = " pyproject.toml | sed -e 's/version = "\(.*\)"/\1/g')
+          if [ "${{ inputs.tag }}" != "${version}" ]; then
+            echo "The input tag does not match the version from pyproject.toml:" >&2
+            echo "${{ inputs.tag }}" >&2
+            echo "${version}" >&2
+            exit 1
+          else
+            echo "Releasing ${version}"
+          fi
+
       - name: "Build and push Docker image"
         uses: docker/build-push-action@v3
         with:
@@ -75,6 +85,6 @@ jobs:
           # Reuse the builder
           cache-from: type=gha
           cache-to: type=gha,mode=max
-          push: ${{ inputs.tag != '' }}
-          tags: ghcr.io/konstin/release-testing2:latest,ghcr.io/konstin/release-testing2:${{ steps.get-tag.outputs.PKG_VERSION }}
+          push: ${{ inputs.tag }}
+          tags: ghcr.io/konstin/release-testing2:latest,ghcr.io/konstin/release-testing2:${{ inputs.tag }}
           labels: ${{ steps.meta.outputs.labels }}
